name: Discourse Theme

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        core_ref: [main, v2026.5.0-latest]
    uses: discourse/.github/.github/workflows/discourse-theme.yml@v1
    with:
      core_ref: ${{ matrix.core_ref }}

  checks:
    needs: ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All matrix jobs passed
        run: |
          if [[ "${{ needs.ci.result }}" != "success" ]]; then
            exit 1
          fi
